### ISSUE TITLE
Have more than one instance of the module on a page

### ISSUE THREAD

**Issue by wilsonge** [JoomJunk/Accordion#2]

**Comment by C-Lodder** [comment]
This has been partially fixed but still buggy.

**Comment by wilsonge** [comment]
My guess is that is because we're including the JavaScript on each module load. We probably should use the JHtml file so we have template overrides but then include it from the helper with a static so it's only ever included once. Like how Joomla include JS files in their JHtml methods (e.g. https://github.com/joomla/joomla-cms/blob/staging/libraries/cms/html/tabs.php#L77 although a class static is better than a static in the function like they have there)

I suspect this would solve the majority of our problems actually :)
